// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp2rTZsOSFBSfR8g8Rgy8QvarIfFp9oTc',
    appId: '1:212715503122:web:569fc03b01bf32c8cfe2cb',
    messagingSenderId: '212715503122',
    projectId: 'costly-fe754',
    authDomain: 'costly-fe754.firebaseapp.com',
    databaseURL: 'https://costly-fe754-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'costly-fe754.firebasestorage.app',
    measurementId: 'G-F6Y3DE4G8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFrKIybioXrdB-5-w8dK0kOs8DE4o7ArI',
    appId: '1:212715503122:android:aeee100b3c62f2bfcfe2cb',
    messagingSenderId: '212715503122',
    projectId: 'costly-fe754',
    databaseURL: 'https://costly-fe754-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'costly-fe754.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARkYNx_5aeQVIQKoA5JSMhI4MRlGLddnA',
    appId: '1:212715503122:ios:cd8f9d46e27237e6cfe2cb',
    messagingSenderId: '212715503122',
    projectId: 'costly-fe754',
    databaseURL: 'https://costly-fe754-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'costly-fe754.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );
}
